backend:
  name: github
  repo: AndrewP1179/test

media_folder: static/assets

collections:
  - name: 'speakers'
    label: 'Speaker'
    folder: 'speakers'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'speakersTemplate' }
      - { name: 'title', label: "Speaker's Name" }
      - { name: 'speakersJob', label: "Speaker's Job" }
      - { name: 'speakersImage', label: "Speaker's Image", widget: 'image' }
      - { name: 'speakersDescription', label: "Speaker's Description", widget: 'markdown' }
  - name: 'blog'
    label: 'Blog'
    folder: 'blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'blogTemplate' }
      - { name: 'title', label: 'Title' }
      - { name: 'path', label: 'Path', default: '/blogs/' }
      - { name: 'date', label: 'Date', widget: 'date', format: 'YYYY-MM-DD' }
      - { name: 'image', label: 'Cover Image', widget: 'image' }
      - { name: 'body', label: 'Body', widget: 'markdown' }
  - name: 'job'
    label: 'Job'
    folder: 'jobs'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'jobTemplate' }
      - { name: 'title', label: 'Title' }
      - { name: 'organization', label: 'Organization' }
      - { name: 'path', label: 'Path', default: '/jobs/' }
      - { name: 'body', label: 'Body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/about/index.md'
        label: 'About'
        name: 'about'
        slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
        fields:
          - { name: 'path', label: 'Path' }
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'aboutTemplate' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'events'
    label: 'Events'
    folder: 'events'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'eventsTemplate' }
      - { name: 'title', label: 'Title' }
      - { name: 'eventsImage', label: "Event's Image", widget: 'image' }
      - { name: 'path', label: 'Path', default: '/events/' }
      - { name: 'time', label: 'Time', widget: 'datetime', format: 'LLL' }
      - { name: 'place', label: 'Place' }
      - { name: 'body', label: 'Description', widget: 'markdown' }
      - {
          name: 'relation',
          label: 'relation',
          widget: 'relation',
          collection: 'speakers',
          searchFields: 'title',
          valueField: 'title',
          displayFields: 'title',
        }
  - label: 'sponsors'
    name: 'sponsors'
    folder: 'sponsorsImages'
    create: true
    identifier_field: galleryImages
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'sponsor' }
      - label: 'sponsor'
        name: 'galleryImages'
        widget: 'list'
        identifier_field: sponsor
        fields:
          - { label: 'sponsor's image', name: 'sponsor', widget: 'image' }
